all:
  children:
    dev:
      vars:
        ansible_user: "{{ ansible_user }}"
        ansible_ssh_private_key_file: "{{ path_priv_key }}"
        ansible_ssh_port: 22
      children:
        master:
          hosts:
            master01:
              ansible_host: 192.168.120.10
        worker:
          hosts:
            worker01:
              ansible_host: 192.168.120.11
